# Generated by Django 4.1.4 on 2023-06-13 12:30

import api.models
import django.core.validators
from django.db import migrations, models
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cidadesatendimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=localflavor.br.models.BRCPFField(max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto_documento',
            field=models.ImageField(null=True, upload_to=api.models.nome_arquivo_foto, validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto_usuario',
            field=models.ImageField(null=True, upload_to=api.models.nome_arquivo_documento, validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nascimento',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome_completo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='reputacao',
            field=models.FloatField(default=5, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.IntegerField(choices=[(1, 'Cliente'), (2, 'Diarista')], null=True),
        ),
    ]
